spring:
  application:
    name: Futbol API
  datasource:
    url: jdbc:h2:file:./data/demo
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console.enabled: true
  jwt:
    secretKey: lLBc+4Z7I0X5pRSbVuY70b0Al8qhze2WyCfKHq3ZKjM=
    tokenExpirationMillis: 86400000
    defaultUser:
      username: test
      password: 12345
      role: ADMIN